import { generateContent } from "../aiServices/contentGenerationService.js";
import pLimit from "p-limit";

/**
 * Summarizes the clusters generated by the semantic pipeline using Gemini.
 * Maps the representative IDs back to discussion objects and prompts the LLM
 * to produce a clean, structured topic summary with evidence.
 * 
 * @param {Object} embeddedDataset The dataset output from the semantic pipeline.
 * @returns {Promise<Array>} Array of structured cluster summaries.
 */
export const summarizeClusters = async (embeddedDataset) => {
    const { discussions, semantic } = embeddedDataset;
    
    if (!semantic || !semantic.clusters) {
        throw new Error("Invalid dataset: Missing semantic clusters data.");
    }
    
    // 1. Build a lookup map for fast discussion retrieval
    const discussionMap = {};
    for (const d of discussions) {
        discussionMap[d.id] = d;
    }
    
    const validClusters = semantic.clusters.filter(c => !c.noise);
    console.log(`ClusterSummarization: Found ${validClusters.length} valid clusters to summarize.`);
    
    const limit = pLimit(3);
    
    // Find max cluster size for confidence normalization
    const maxClusterSize = validClusters.length > 0 ? Math.max(...validClusters.map(c => c.size)) : 1;

    // 2. Iterate and summarize each cluster concurrently
    const summarizeCluster = async (cluster) => {
        const representativeDocs = cluster.representativeIds.map(id => {
            const d = discussionMap[id];
            
            // Intelligent Truncation Budgeting
            const safeTitle = d.title ? (d.title.length > 200 ? d.title.substring(0, 200) + "..." : d.title) : "";
            const safeBody = d.body ? (d.body.length > 1800 ? d.body.substring(0, 1800) + "...[TRUNCATED]" : d.body) : "";
            
            const limitedComments = d.comments ? d.comments.slice(0, 3).map(c => {
                return c.length > 700 ? c.substring(0, 700) + "...[TRUNCATED]" : c;
            }) : [];
            
            const docString = `Title: ${safeTitle}\nBody: ${safeBody}\nComments:\n${limitedComments.join('\n')}`;
            
            return { text: docString };
        });
        
        const charLength = JSON.stringify(representativeDocs).length;
        console.log(`ClusterSummarization: Cluster ${cluster.id} payload length: ${charLength} chars`);

        if (representativeDocs.length === 0) return null;

        // Confidence Calculation
        // Normalize size so largest cluster has sizeFactor = 1.0
        const sizeFactor = cluster.size / maxClusterSize; 
        const cohesion = cluster.cohesion || 0.5; // fallback to 0.5 if missing
        
        // E.g., confidence = (sizeFactor * 0.4) + (cohesion * 0.6).
        // A large, highly cohesive cluster gets close to 1.0.
        const confidence = parseFloat(((sizeFactor * 0.4) + (cohesion * 0.6)).toFixed(2));

        const prompt = `
You are an expert Chief Strategy Officer. I will provide you with a cluster of highly related discussions from a community forum. 
These discussions were mathematically grouped together based on semantic similarity.

Your task is to analyze these representative discussions and extract structured business intelligence.

Here are the representative discussions for this cluster:
${JSON.stringify(representativeDocs, null, 2)}

Return a raw JSON object (without markdown code blocks) with the following exact structure:
{
  "topic": "A short, descriptive 3-5 word title for this topic cluster",
  "overview": "A robust 3-4 sentence explanation of the prevailing sentiment and core issues discussed",
  "positiveSignals": ["A specific positive observation", "Another positive signal"],
  "negativeSignals": ["A specific complaint or pain point", "Another negative signal"],
  "customerRequests": ["A feature request or need mentioned by users"],
  "competitors": ["Any competitors mentioned, or empty array if none"],
  "evidence": ["A specific quote extracted from the provided text", "Another quote"]
}
`;
        console.time(`Summarizing Cluster ${cluster.id}`);
        try {
            const geminiText = await generateContent(prompt);
            const cleanedText = geminiText.replace(/```json|```/g, "").trim();
            const result = JSON.parse(cleanedText);
            
            console.timeEnd(`Summarizing Cluster ${cluster.id}`);
            return {
                clusterId: cluster.id,
                clusterSize: cluster.size,
                confidence: confidence,
                topic: result.topic,
                overview: result.overview,
                positiveSignals: result.positiveSignals || [],
                negativeSignals: result.negativeSignals || [],
                customerRequests: result.customerRequests || [],
                competitors: result.competitors || [],
                evidence: result.evidence || [],
                representativeIds: cluster.representativeIds || []
            };
        } catch (error) {
            console.error(`ClusterSummarization: Failed to summarize cluster ${cluster.id}`, error);
            console.timeEnd(`Summarizing Cluster ${cluster.id}`);
            return {
                clusterId: cluster.id,
                clusterSize: cluster.size,
                confidence: confidence,
                topic: "Error Generating Topic",
                overview: "Failed to generate summary.",
                positiveSignals: [],
                negativeSignals: [],
                customerRequests: [],
                competitors: [],
                evidence: []
            };
        }
    };

    const summaries = await Promise.all(
        validClusters.map(cluster => limit(() => summarizeCluster(cluster)))
    );
    
    // Filter out any nulls from empty clusters
    return summaries.filter(s => s !== null);
};
